services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - /mongodb/challenge:/data/db
    networks:
      - main_network
  api:
    build: ./backend/
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URI: mongodb://root:changeme@database:27017/
    networks:
      - main_network
  webapp:
    build: ./frontend/
    restart: always
    depends_on:
      - api
    networks:
      - main_network
  proxy:
    build: ./proxy/
    restart: always
    depends_on:
      - api
      - webapp
    networks:
      - main_network
    ports:
      - 1997:80

networks:
  main_network: